language: python
python:
  - "3.5"
  - "3.6"

services:
  - docker

install:
  - docker build --build-arg BUILDER_UID=$(id -u) -t aodn/python-aodncore .

script:
  - docker run -w /app --mount type=bind,source="$(pwd)",target=/app aodn/python-aodncore /bin/sh -c "pip install --user -e . .[testing] pytest pytest-cov codecov; pytest --cov=./"

after_success:
  - codecov
