language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - libudunits2-dev

install:
  - pip install -c constraints.txt -r requirements.txt
  - pip install coverage
  - pip install codecov

script:
  - coverage run setup.py test

after_success:
  - codecov
