language: python
python:
  - "2.7"

install:
  - wget https://s3-ap-southeast-2.amazonaws.com/imos-binary/jobs/compliance_checker_prod/compliance_checker_prod-latest.whl
  - wget https://s3-ap-southeast-2.amazonaws.com/imos-binary/jobs/cc_plugin_imos_prod/cc_plugin_imos_prod-latest.whl
  - pip install compliance_checker_prod-latest.whl
  - pip install cc_plugin_imos_prod-latest.whl
  - pip install -r requirements.txt

script:
  - python setup.py test
