name: Release

on:
  release:
      types:
        - created

jobs:
  release:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Install build tools
        run: python -m pip install build --user
      - name: Build wheels
        run: python -m build --outdir wheels

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          files: wheels/*.whl
          body: ${{ steps.build_changelog.outputs.changelog }}
