name: Build Release

on:
  release:
      types:
        - created

jobs:
  build-and-publish:
    name: create release with artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Install build tools
        run: python -m pip install build --user
      - name: Build wheels
        run: python -m build --outdir wheels
      - name: Attach wheel to release
        uses: softprops/action-gh-release@v1
        with:
          files: wheels/*.whl
      - name: Upload to S3 bucket
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          aws-bucket: ${{ secrets.AWS_ARTIFACT_BUCKET }}
          file-path: wheels/*.whl
          destination-dir: /releases/python-aodncore
