name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Install build tools
        run: python -m pip install build --user

      - name: Build wheels
        run: python -m build --outdir wheels

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wheels/*.whl
