name: python-aodncore

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aodn/aodncore-build:latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install -r test_requirements.txt
        pip install pytest-cov
    - name: Test with pytest
      run: pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      if: ${{ !env.ACT }}
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
